.PHONY: clean All

All:
	@echo "----------Building project:[ test - Linux_Debug ]----------"
	@"$(MAKE)" -f  "test.mk"
clean:
	@echo "----------Cleaning project:[ test - Linux_Debug ]----------"
	@"$(MAKE)" -f  "test.mk" clean
